actionsDiagnosis = {}
actionsDiagnosis['A030'] = '' #SHIGELOSIS DEBIDA A SHIGELLA DYSENTERIAE
actionsDiagnosis['A031'] = '' #SHIGELOSIS DEBIDA A SHIGELLA FLEXNERI
actionsDiagnosis['A040'] = '' #INFECCION DEBIDA A ESCHERICHIA COLI ENTEROPATOGENA
actionsDiagnosis['A046'] = '' #ENTERITIS DEBIDA A YERSINIA ENTEROCOLITICA
actionsDiagnosis['A048'] = '' #OTRAS INFECCIONES INTESTINALES BACTERIANAS ESPECIFICADAS
actionsDiagnosis['A060'] = '' #DISENTERIA AMEBIANA AGUDA
actionsDiagnosis['A061'] = '' #AMEBIASIS INTESTINAL CRONICA
actionsDiagnosis['A063'] = '' #AMEBOMA INTESTINAL
actionsDiagnosis['A078'] = '' #OTRAS ENFERMEDADES INTESTINALES ESPECIFICADAS DEBIDAS A PROTOZOARIOS
actionsDiagnosis['A085'] = '' #OTRAS INFECCIONES INTESTINALES ESPECIFICADAS
actionsDiagnosis['A09X'] = '' #DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN INFECCIOSO
actionsDiagnosis['A152'] = '' #TUBERCULOSIS DEL PULMON, CONFIRMADA HISTOLOGICAMENTE
actionsDiagnosis['A153'] = '' #TUBERCULOSIS DEL PULMON , CONFIRMADA POR MEDIOS NO ESPECIFICADOS
actionsDiagnosis['A164'] = '' #TUBERCULOSIS DE LARINGE, TRAQUEA Y BRONQUIOS, SIN MENCION DE CONFIRMACION BACTERIOLOGICA O HISTOLOGICA
actionsDiagnosis['A167'] = '' #TUBERCULOSIS RESPIRATORIA PRIMARIA, SIN MENCION DE CONFIRMACION BACTERIOLOGICA E HISTOLOGICA
actionsDiagnosis['A168'] = '' #OTRAS TUBERCULOSIS RESPIRATORIAS, SIN MENCION DE CONFIRMACION
actionsDiagnosis['A201'] = '' #PESTE CELULOCUTANEA
actionsDiagnosis['A207'] = '' #PESTE SEPTICEMICA
actionsDiagnosis['A219'] = '' #TULAREMIA , NO ESPECIFICADA
actionsDiagnosis['A220'] = '' #CARBUNCO CUTANEO
actionsDiagnosis['A418'] = '' #OTRAS SEPTICEMIAS ESPECIFICADAS
actionsDiagnosis['A419'] = 'VAR_0502 = B' #SEPTICEMIA, NO ESPECIFICADA
actionsDiagnosis['A499'] = '' #INFECCION BACTERIANA, NO ESPECIFICADA
actionsDiagnosis['A501'] = 'SIFILIS = True' #SIFILIS CONGENITA PRECOZ, LATENTE
actionsDiagnosis['A507'] = 'SIFILIS = True' #SIFILIS CONGENITA TARDIA, SIN OTRA ESPECIFICACION
actionsDiagnosis['A509'] = 'SIFILIS = True' #SIFILIS CONGENITA, SIN OTRA ESPECIFICACIÓN
actionsDiagnosis['A510'] = 'SIFILIS = True' #SIFILIS GENITAL PRIMARIA
actionsDiagnosis['A512'] = 'SIFILIS = True' #SIFILIS PRIMARIA EN OTROS SITIOS
actionsDiagnosis['A528'] = 'SIFILIS = True' #SIFILIS TARDIA, LATENTE
actionsDiagnosis['A529'] = 'SIFILIS = True' #SIFILIS TARDIA, NO ESPECIFICADA
actionsDiagnosis['A530'] = 'SIFILIS = True' #SIFILIS LATENTE, NO ESPECIFICADA COMO PRECOZ O TARDIA
actionsDiagnosis['A539'] = 'SIFILIS = True' #SIFILIS, NO ESPECIFICADA
actionsDiagnosis['A630'] = '' #VERRUGAS (VENEREAS) ANOGENITALES
actionsDiagnosis['A689'] = '' #FIEBRE RECURRENTE, NO ESPECIFICADA
actionsDiagnosis['B07X'] = '' #VERRUGAS VIRICAS
actionsDiagnosis['B203'] = '' #ENFERMEDAD POR VIH, RESULTANTE EN OTRAS INFECCIONES VIRALES
actionsDiagnosis['B24X'] = '' #ENFERMEDAD POR VIRUS DE LA INMUNODEFICIENCIA HUMANA (VIH), SIN OTRA ESPECIFICACION
actionsDiagnosis['B269'] = '' #PAROTIDITIS, SIN COMPLICACIONES
actionsDiagnosis['B356'] = '' #TIÑA INGUINAL [TINEA CRURIS]
actionsDiagnosis['B373'] = '' #CANDIDIASIS DE LA VULVA Y DE LA VAGINA (N77.1*)
actionsDiagnosis['B529'] = '' #PALUDISMO DEBIDO A PLASMODIUM MALARIAE, SIN COMPLICACIONES
actionsDiagnosis['B589'] = '' #TOXOPLASMOSIS, NO ESPECIFICADA
actionsDiagnosis['B86X'] = '' #ESCABIOSIS
actionsDiagnosis['B951'] = '' #ESTREPTOCOCO, GRUPO B, COMO CAUSA DE ENFERMEDADES CLASIFICADAS EN OTROS CAPITULOS
actionsDiagnosis['B977'] = '' #PAPILOMAVIRUS COMO CAUSA DE ENFERMEDADES CLASIFICADAS EN OTROS CAPITULOS
actionsDiagnosis['C509'] = '' #TUMOR MALIGNO DE LA MAMA, PARTE NO ESPECIFICADA
actionsDiagnosis['C530'] = '' #TUMOR MALIGNO DEL ENDOCERVIX
actionsDiagnosis['C531'] = '' #TUMOR MALIGNO DE EXOCERVIX
actionsDiagnosis['C678'] = ''	#LESION DE SITIOS CONTIGUOS DE LA VEJIGA
actionsDiagnosis['D259'] = '' #MIOMATOSIS UTERINA
actionsDiagnosis['D464'] = 'VAR_0620 = B' #ANEMIA REFRACTARIA, SIN OTRA ESPECIFICACION
actionsDiagnosis['D500'] = 'VAR_0620 = B' #ANEMIA POR DEFICIENCIA DE HIERRO SECUNDARIA A PERDIDA DE SANGRE (CRONICA)
actionsDiagnosis['D508'] = 'VAR_0620 = B' #OTRAS ANEMIAS POR DEFICIENCIA DE HIERRO
actionsDiagnosis['D509'] = 'VAR_0620 = B' #ANEMIA POR DEFICIENCIA DE HIERRO SIN OTRA ESPECIFICACION
actionsDiagnosis['D531'] = 'VAR_0620 = B' #OTRAS ANEMIAS MEGALOBLASTICAS, NO CLASIFICADAS EN OTRA PARTE
actionsDiagnosis['D538'] = 'VAR_0620 = B' #OTRAS ANEMIAS NUTRICIONALES ESPECIFICADAS
actionsDiagnosis['D539'] = 'VAR_0620 = B' #ANEMIA NUTRICIONAL, NO ESPECIFICADA
actionsDiagnosis['D570'] = 'VAR_0621 = B' #ANEMIA FALCIFORME CON CRISIS
actionsDiagnosis['D571'] = 'VAR_0621 = B' #ANEMIA FALCIFORME SIN CRISIS
actionsDiagnosis['D573'] = '' #RASGO DREPANOCITICO
actionsDiagnosis['D588'] = 'VAR_0620 = B' #OTRAS ANEMIAS HEMOLITICAS HEREDITARIAS ESPECIFICADAS
actionsDiagnosis['D62X'] = 'VAR_0620 = B' #ANEMIA POSTHEMORRAGICA AGUDA
actionsDiagnosis['D648'] = 'VAR_0620 = B' #OTRAS ANEMIAS ESPECIFICADAS
actionsDiagnosis['D649'] = 'VAR_0620 = B' #ANEMIA DE TIPO NO ESPECIFICADO
actionsDiagnosis['D65X'] = 'VAR_0498 = B' #SINDROME HELLP
actionsDiagnosis['D689'] = 'VAR_0602 = B' #DEFECTO DE LA COAGULACION, NO ESPECIFICADO
actionsDiagnosis['D696'] = '' #TROMBOCITOPENIA NO ESPECIFICADA
actionsDiagnosis['E038'] = 'VAR_0610 = B' #OTROS HIPOTIROIDISMOS ESPECIFICADOS
actionsDiagnosis['E039'] = 'VAR_0610 = B' #HIPOTIROIDISMO, NO ESPECIFICADO
actionsDiagnosis['E078'] = '' #OTROS TRASTORNOS ESPECIFICADOS DE LA GLANDULA TIROIDES
actionsDiagnosis['E108'] = 'VAR_0606 = B' #DIABETES MELLITUS INSULINODEPENDIENTE CON COMPLICACIONES NO ESPECIFICADAS
actionsDiagnosis['E109'] = 'VAR_0606 = B' #DIABETES MELLITUS INSULINODEPENDIENTE SIN MENCION DE COMPLICACION
actionsDiagnosis['E119'] = 'VAR_0607 = B' #DIABETES MELLITUS NO INSULINODEPENDIENTE SIN MENCION DE COMPLICACION
actionsDiagnosis['E128'] = 'VAR_0607 = B' #DIABETES MELLITUS ASOCIADA CON DESNUTRICION CON COMPLICACIONES NO ESPECIFICADAS
actionsDiagnosis['E141'] = 'VAR_0607 = B' #DIABETES MELLITUS, NO ESPECIFICADA CON CETOACIDOSIS
actionsDiagnosis['E660'] = '' #OBESIDAD DEBIDA A EXCESO DE CALORIAS
actionsDiagnosis['E668'] = '' #OTROS TIPOS DE OBESIDAD
actionsDiagnosis['E669'] = '' #OBESIDAD, NO ESPECIFICADA
actionsDiagnosis['E872'] = '' #ACIDOSIS
actionsDiagnosis['E873'] = '' #ALCALOSIS
actionsDiagnosis['E889'] = '' #TRASTORNO METABOLICO, NO ESPECIFICADO
actionsDiagnosis["F190"] = ''
actionsDiagnosis['F123'] = '' #TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE CANNABINOIDES: ESTADO DE ABSTINENCIA
actionsDiagnosis['F209'] = '' #ESQUIZOFRENIA, NO ESPECIFICADA
actionsDiagnosis['F328'] = '' #OTROS EPISODIOS DEPRESIVOS
actionsDiagnosis['F530'] = '' #TRASTORNOS MENTALES Y DEL COMPORTAMIENTO LEVES, ASOCIADOS CON EL PUERPERIO, NO CLASIFICADOS EN OTRA PARTE
actionsDiagnosis['G111'] = '' #ATAXIA CEREBELOSA DE INICIACION TEMPRANA
actionsDiagnosis['G403'] = '' #EPILEPSIA Y SINDROMES EPILEPTICOS IDIOPATICOS GENERALIZADOS
actionsDiagnosis['G404'] = '' #OTRAS EPILEPSIAS Y SINDROMES EPILEPTICOS GENERALIZADOS
actionsDiagnosis['G442'] = '' #CEFALEA DEBIDA A TENSION
actionsDiagnosis['G448'] = '' #OTROS SINDROMES DE CEFALEA ESPECIFICADOS
actionsDiagnosis['G510'] = '' #PARALISIS DE BELL
actionsDiagnosis['G519'] = '' #TRASTORNOS DEL NERVIO FACIAL, NO ESPECIFICADO
actionsDiagnosis['H474'] = '' #TRASTORNOS DEL QUIASMA OPTICO
actionsDiagnosis['I10X'] = 'VAR_0650 = B' #HIPERTENSION ESENCIAL (PRIMARIA)
actionsDiagnosis['I158'] = 'VAR_0650 = B' #OTROS TIPOS DE HIPERTENSION SECUNDARIA
actionsDiagnosis['I159'] = 'VAR_0650 = B' #HIPERTENSION SECUNDARIA, NO ESPECIFICADA
actionsDiagnosis['I341'] = 'VAR_0617 = B' #PROLAPSO (DE LA VALVULA) MITRAL
actionsDiagnosis['I499'] = '' #ARRITMIA CARDIACA, NO ESPECIFICADA
actionsDiagnosis['I679'] = '' #ENFERMEDAD CEREBROVASCULAR, NO ESPECIFICADA
actionsDiagnosis['J80X'] = ''     #SINDROME DE DIFICULTAD RESPIRATORIA DEL ADULTO
actionsDiagnosis['J00X'] = '' #RINOFARINGITIS AGUDA (RESFRIADO COMUN)
actionsDiagnosis['J209'] = '' #BRONQUITIS AGUDA, NO ESPECIFICADA
actionsDiagnosis['J189'] = '' #NEUMONIA, NO ESPECIFICADA
actionsDiagnosis['J22X'] = 'VAR_0566 = B; VAR_0597 = ViasRespiratorias' #INFECCION AGUDA NO ESPECIFICADA DE LAS VIAS RESPIRATORIAS INFERIORES
actionsDiagnosis['J459'] = '' #ASMA, NO ESPECIFICADA
actionsDiagnosis['J46X'] = '' #ESTADO ASMATICO
actionsDiagnosis['J960'] = '' #INSUFICIENCIA RESPIRATORIA AGUDA
actionsDiagnosis['K289'] = '' #ULCERA GASTROYEYUNAL NO ESPECIFICADA COMO AGUDA NI CRONICA, SIN HEMORRAGIA NI PERFORACION
actionsDiagnosis['K297'] = '' #GASTRITIS, NO ESPECIFICADA
actionsDiagnosis['K590'] = '' #CONSTIPACION
actionsDiagnosis['K808'] = '' #OTRAS COLELITIASIS
actionsDiagnosis['L038'] = '' #CELULITIS DE OTROS SITIOS
actionsDiagnosis['L299'] = '' #PRURITO, NO ESPECIFICADO
actionsDiagnosis['M080'] = '' #ARTRITIS REUMATOIDE JUVENIL
actionsDiagnosis['M329'] = '' #LUPUS ERITEMATOSO SISTEMICO, SIN OTRA ESPECIFICACION
actionsDiagnosis['M546'] = '' #DOLOR EN LA COLUMNA DORSAL
actionsDiagnosis['N179'] = '' #INSUFICIENCIA RENAL AGUDA, NO ESPECIFICADA
actionsDiagnosis['N218'] = '' #OTROS CALCULOS DE LAS VIAS URINARIAS INFERIORES
actionsDiagnosis['N23X'] = '' #COLICO RENAL, NO ESPECIFICADO
actionsDiagnosis['N300'] = '' #CISTITIS AGUDAS
actionsDiagnosis['N390'] = '' #INFECCION DE VIAS URINARIAS, SITIO NO ESPECIFICADO
actionsDiagnosis['N760'] = '' #VAGINITIS AGUDA
actionsDiagnosis['N761'] = '' #VAGINITIS SUBAGUDA Y CRONICA
actionsDiagnosis['N768'] = '' #OTRAS INFLAMACIONES ESPECIFICADAS DE LA VAGINA Y DE LA VULVA
actionsDiagnosis['N771'] = '' #VAGINITIS, VULVITIS Y VULVOVAGINITIS EN ENFERMEDADES INFECCIOSAS Y PARASITARIAS CLASIFICADAS EN OTRA PARTE
actionsDiagnosis['N808'] = 'VAR_0500 = B' #OTRAS ENDOMETRIOSIS
actionsDiagnosis['N855'] = '' #INVERSION DEL UTERO
actionsDiagnosis['N912'] = '' #AMENORREA, SIN OTRA ESPECIFICACION
actionsDiagnosis['N938'] = '' #OTRAS HEMORRAGIAS UTERINAS O VAGINALES ANORMALES ESPECIFICADAS
actionsDiagnosis['N939'] = '' #HEMORRAGIA VAGINAL Y UTERINA ANORMAL, NO ESPECIFICADA
actionsDiagnosis['N96X'] = '' #ABORTADORA HABITUAL
actionsDiagnosis['O000'] = '' #EMBARAZO ABDOMINAL
actionsDiagnosis['O009'] = 'VAR_0505 = B' #EMBARAZO ECTOPICO, NO ESPECIFICADO
actionsDiagnosis['O021'] = '' #ABORTO RETENIDO
actionsDiagnosis['O028'] = '' #OTROS PRODUCTOS ANORMALES ESPECIFICADOS DE LA CONCEPCION
actionsDiagnosis['O030'] = '' #ABORTO ESPONTANEO: INCOMPLETO, COMPLICADO CON INFECCIÓN GENITAL Y PELVIANA
actionsDiagnosis['O033'] = '' #ABORTO ESPONTANEO: INCOMPLETO, CON OTRAS COMPLICACIONES ESPECIFICADAS Y LAS NO ESPECIFICADAS
actionsDiagnosis['O034'] = '' #ABORTO ESPONTANEO: INCOMPLETO, SIN COMPLICACION
actionsDiagnosis['O038'] = '' #ABORTO ESPONTANEO: COMPLETO O NO ESPECIFICADO, CON OTRAS COMPLICACIONES ESPECIFICADAS Y LAS NO ESPECIFICADAS
actionsDiagnosis['O039'] = '' #ABORTO ESPONTANEO: COMPLETO O NO ESPECIFICADO, SIN COMPLICACION
actionsDiagnosis['O041'] = '' #ABORTO MEDICO: INCOMPLETO, COMPLICADO POR HEMORRAGIA EXCESIVA O TARDIA
actionsDiagnosis['O044'] = '' #ABORTO MEDICO: INCOMPLETO, SIN COMPLICACION
actionsDiagnosis['O045'] = '' #ABORTO MEDICO: COMPLETO O NO ESPECIFICADO, COMPLICADO CON INFECCION GENITAL Y PELVIANA
actionsDiagnosis['O049'] = '' #ABORTO MEDICO: COMPLETO O NO ESPECIFICADO, SIN COMPLICACION
actionsDiagnosis['O054'] = '' #OTRO ABORTO: INCOMPLETO, SIN COMPLICACION
actionsDiagnosis['O058'] = '' #OTRO ABORTO: COMPLETO O NO ESPECIFICADO, CON OTRAS COMPLICACIONES ESPECIFICADAS Y LAS NO ESPECIFICADAS
actionsDiagnosis['O060'] = '' #ABORTO SEPTICO
actionsDiagnosis['O061'] = '' #ABORTO NO ESPECIFICADO: INCOMPLETO, COMPLICADO POR HEMORRAGIA EXCESIVA O TARDIA
actionsDiagnosis['O064'] = '' #ABORTO NO ESPECIFICADO: INCOMPLETO, SIN COMPLICACION
actionsDiagnosis['O069'] = '' #ABORTO NO ESPECIFICADO: COMPLETO O NO ESPECIFICADO, SIN COMPLICACION
actionsDiagnosis['O070'] = '' #FALLA DE LA INDUCCION MEDICA DEL ABORTO, COMPLICADO CON INFECCIÓN GENITAL Y PELVIANA
actionsDiagnosis['O079'] = '' #OTROS INTENTOS FALLIDOS DE ABORTO Y LOS NO ESPECIFICADOS, SIN COMPLICACION
actionsDiagnosis['O088'] = '' #OTRAS COMPLICACIONES CONSECUTIVAS AL ABORTO, AL EMBARAZO ECTOPICO Y AL EMBARAZO MOLAR
actionsDiagnosis['O100'] = 'VAR_0653 = B' #HIPERTENSION CRONICA + PREECLAMPSIA SOBREAGREGADA
actionsDiagnosis['O104'] = 'VAR_0650 = B' #HIPERTENSION SECUNDARIA PREEXISTENTE QUE COMPLICA EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O109'] = 'VAR_0650 = B' #HIPERTENSION PREEXISTENTE NO ESPECIFICADA, QUE COMPLICA EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O11X'] = '' #TRASTORNOS HIPERTENSIVOS PREEXISTENTES, CON PROTEINURIA AGREGADA
actionsDiagnosis['O120'] = '' #EDEMA GESTACIONAL
actionsDiagnosis['O121'] = '' #PROTEINURIA GESTACIONAL
actionsDiagnosis['O13X'] = 'VAR_0652 = B' #HIPERTENSION GESTACIONAL (INDUCIDA POR EL EMBARAZO) SIN PROTEINURIA SIGNIFICATIVA
actionsDiagnosis['O140'] = 'VAR_0260 = B' #PREECLAMPSIA MODERADA
actionsDiagnosis['O141'] = 'VAR_0651 = B' #PREECLAMPSIA SEVERA
actionsDiagnosis['O149'] = 'VAR_0260 = B' #PREECLAMPSIA, NO ESPECIFICADA
actionsDiagnosis['O150'] = 'VAR_0260 = B' #PREECLAMPSIA EN EL EMBARAZO
actionsDiagnosis['O151'] = 'VAR_0260 = B' #PREECLAMPSIA DURANTE EL TRABAJO DE PARTO
actionsDiagnosis['O152'] = 'VAR_0260 = B' #PREECLAMPSIA EN EL PUERPERIO
actionsDiagnosis['O159'] = 'VAR_0261 = B' #Eclampsia
actionsDiagnosis['O16X'] = 'VAR_0258 = B' #HIPERTENSION MATERNA, NO ESPECIFICADA
actionsDiagnosis['O200'] = '' #AMENAZA DE ABORTO
actionsDiagnosis['O209'] = 'VAR_0508 = B' #HEMORRAGIA PRECOZ DEL EMBARAZO, SIN OTRA ESPECIFICACION
actionsDiagnosis['O218'] = '' #OTROS VOMITOS QUE COMPLICAN EL EMBARAZO
actionsDiagnosis['O219'] = '' #VOMITOS DEL EMBARAZO, NO ESPECIFICADO
actionsDiagnosis['O229'] = '' #COMPLICACION VENOSA NO ESPECIFICADA EN EL EMBARAZO
actionsDiagnosis['O233'] = '' #INFECCION DE OTRAS PARTES DE LAS VIAS URINARIAS EN EL EMBARAZO
actionsDiagnosis['O234'] = '' #INFECCION DE LAS VIAS URINARIAS EN EL EMBARAZO.
actionsDiagnosis['O235'] = '' #INFECCION GENITAL EN EL EMBARAZO
actionsDiagnosis['O244'] = 'VAR_0608 = B' #DIABETES EN EL EMBARAZO
actionsDiagnosis['O249'] = 'VAR_0608 = B' #DIABETES MELLITUS NO ESPECIFICADA, EN EL EMBARAZO
actionsDiagnosis['O260'] = '' #AUMENTO EXCESIVO DE PESO EN EL EMBARAZO
actionsDiagnosis['O262'] = '' #ATENCION DEL EMBARAZO EN UNA ABORTADORA HABITUAL
actionsDiagnosis['O267'] = '' #SUBLUXACION DE LA SINFISIS (DEL PUBIS) EN EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O268'] = '' #OTRAS COMPLICACIONES ESPECIFICADAS RELACIONADAS CON EL EMBARAZO
actionsDiagnosis['O269'] = '' #COMPLICACION RELACIONADA CON EL EMBARAZO, NO ESPECIFICADA
actionsDiagnosis['O282'] = '' #HALLAZGO CITOLOGICO ANORMAL EN EL EXAMEN PRENATAL DE LA MADRE
actionsDiagnosis['O283'] = '' #HALLAZGO ULTRASONICO ANORMAL EN EL EXAMEN PRENATAL DE LA MADRE
actionsDiagnosis['O288'] = '' #OTROS HALLAZGOS ANORMALES EN EL EXAMEN PRENATAL DE LA MADRE
actionsDiagnosis['O300'] = '' #EMBARAZO GEMELAR
actionsDiagnosis['O312'] = '' #EMBARAZO QUE CONTINUA DESPUES DE LA MUERTE INTRAUTERINA DE UN FETO O MAS
actionsDiagnosis['O318'] = '' #OTRAS COMPLICACIONES ESPECIFICADAS DEL EMBARAZO
actionsDiagnosis['O321'] = 'VAR_0202 = B' #FETO EN PODALICA
actionsDiagnosis['O322'] = 'VAR_0202 = C' #FETO EN TRANSVERSA
actionsDiagnosis['O323'] = '' #FETO CARA, DE FRENTE O DE MENTON
actionsDiagnosis['O326'] = '' #ATENCION MATERNA POR PRESENTACION COMPUESTA
actionsDiagnosis['O328'] = '' #ATENCION MATERNA POR OTRAS PRESENTACIONES ANORMALES DEL FETO
actionsDiagnosis['O329'] = '' #ATENCION MATERNA POR PRESENTACION ANORMAL NO ESPECIFICADA DEL FETO
actionsDiagnosis['O330'] = '' #ATENCION MATERNA POR DESPROPORCION DEBIDA A DEFORMIDAD DE LA PELVIS OSEA EN LA MADRE
actionsDiagnosis['O331'] = '' #ATENCION MATERNA POR DESPROPORCION DEBIDA A ESTRECHEZ GENERAL DE LA PELVIS
actionsDiagnosis['O332'] = '' #ATENCION MATERNA POR DESPROPORCION DEBIDA A DISMINUCION DEL ESTRECHO SUPERIOR DE LA PELVIS
actionsDiagnosis['O333'] = '' #ATENCION MATERNA POR DESPROPORCION DEBIDA A DISMINUCION DEL ESTRECHO INFERIOR DE LA PELVIS
actionsDiagnosis['O334'] = '' #DESPROPORCION CEFALO PELVICA
actionsDiagnosis['O335'] = '' #FETO MACROSOMICO
actionsDiagnosis['O342'] = '' #CESAREA ANTERIOR 
actionsDiagnosis['O347'] = '' #ATENCION MATERNA POR ANORMALIDAD DE LA VULVA Y DEL PERINEO
actionsDiagnosis['O354'] = '' #ATENCION MATERNA POR (PRESUNTA) LESION AL FETO DEBIDA AL ALCOHOL
actionsDiagnosis['O359'] = 'VAR_0335 = C' #FETO CON MALFORMACIONES CONGENITAS
actionsDiagnosis['O360'] = '' #INCOMPATIBILIDAD DE RH
actionsDiagnosis['O361'] = '' #ATENCION MATERNA POR OTRA ISOINMUNIZACION
actionsDiagnosis['O362'] = '' #ATENCION MATERNA POR HIDROPESIA FETAL
actionsDiagnosis['O363'] = '' #ESTADO FETAL NO SATISFACTORIO
actionsDiagnosis['O364'] = '' #OBITO FETAL
actionsDiagnosis['O365'] = 'VAR_0634 = B' #RETARDO DEL CRECIMIENTO INTRAUTERINO
actionsDiagnosis['O366'] = '' #ATENCION MATERNA POR CRECIMIENTO FETAL EXCESIVO
actionsDiagnosis['O367'] = '' #ATENCION MATERNA POR FETO VIABLE EN EMBARAZO ABDOMINAL
actionsDiagnosis['O368'] = '' #ATENCION MATERNA POR OTROS PROBLEMAS FETALES ESPECIFICADOS
actionsDiagnosis['O40X'] = 'VAR_0632 = B' #POLIHIDRAMNIOS
actionsDiagnosis['O410'] = 'VAR_0631 = B' #OLIGOHIDRAMNIOS
actionsDiagnosis['O411'] = '' #INFECCIÓN DE LA BOLSA AMNIOTICA O DE LAS MEMBRANAS.
actionsDiagnosis['O418'] = '' #OTROS TRASTORNOS ESPECIFICADOS DEL LIQUIDO AMNIOTICO Y DE LAS MEMBRANAS
actionsDiagnosis['O419'] = '' #TRASTORNO DEL LIQUIDO AMNIOTICO Y DE LAS MEMBRANAS, NO ESPECIFICADO
actionsDiagnosis['O420'] = 'VAR_0630 = B' #RUPTURA PREMATURA DE LAS MEMBRANAS, E INICIO DEL TRABAJO DE PARTO DENTRO DE LAS 24 HORAS
actionsDiagnosis['O421'] = 'VAR_0630 = B' #RUPTURA PREMATURA DE LAS MEMBRANAS, E INICIO DEL TRABAJO DE PARTO DESPUÉS DE LAS 24 HORAS
actionsDiagnosis['O422'] = 'VAR_0630 = B' #RUPTURA PREMATURA DE LAS MEMBRANAS, TRABAJO DE PARTO RETRASADO POR LA TERAPEUTICA
actionsDiagnosis['O429'] = 'VAR_0630 = B' #RUPTURA PREMATURA DE MEMBRANAS
actionsDiagnosis['O438'] = '' #OTROS TRASTORNOS PLACENTARIOS
actionsDiagnosis['O440'] = '' #PLACENTA PREVIA CON ESPECIFICACIÓN DE QUE NO HUBO HEMORRAGIA
actionsDiagnosis['O441'] = 'VAR_0506 = B' #PLACENTA PREVIA CON HEMORRAGIA
actionsDiagnosis['O458'] = 'VAR_0508 = B' #OTROS DESPRENDIMIENTOS PREMATUROS DE LA PLACENTA
actionsDiagnosis['O459'] = 'VAR_0508 = B' #DESPRENDIMIENTO PREMATURO DE PLACENTA SIN OTRA ESPECIFICACIÓN.
actionsDiagnosis['O470'] = '' #AMENAZA DE TRABAJO DE PARTO PRETERMINO
actionsDiagnosis['O471'] = '' #FALSO TRABAJO DE PARTO ANTES DE LA 37 Y MAS SEMANAS COMPLETAS DE GESTACION
actionsDiagnosis['O479'] = '' #Preparto
actionsDiagnosis['O48X'] = '' #EMBARAZO PROLONGADO
actionsDiagnosis['O60X'] = '' #PARTO PREMATURO
actionsDiagnosis['O610'] = '' #INDUCCION FALLIDA
actionsDiagnosis['O611'] = '' #FRACASO DE LA INDUCCION INSTRUMENTAL DEL TRABAJO DE PARTO
actionsDiagnosis['O618'] = '' #OTROS FRACASOS DE LA INDUCCION DEL TRABAJO DE PARTO
actionsDiagnosis['O620'] = '' #CONTRACCIONES PRIMARIAS INADECUADAS
actionsDiagnosis['O623'] = '' #TRABAJO DE PARTO PRECIPITADO
actionsDiagnosis['O624'] = '' #CONTRACCIONES UTERINAS HIPERTONICAS, INCOORDINADAS Y PROLONGADAS
actionsDiagnosis['O628'] = '' #OTRAS ANOMALIAS DINAMICAS DEL TRABAJO DE PARTO
actionsDiagnosis['O629'] = '' #ANOMALIA DINAMICA DEL TRABAJO DE PARTO, NO ESPECIFICADA
actionsDiagnosis['O630'] = '' #PROLONGACION DEL PRIMER PERIODO (DEL TRABAJO DE PARTO)
actionsDiagnosis['O631'] = '' #EXPULSIVO PROLONGADO
actionsDiagnosis['O639'] = '' #TRABAJO DE PARTO PROLONGADO, NO ESPECIFICADO
actionsDiagnosis['O641'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A PRESENTACION DE NALGAS
actionsDiagnosis['O649'] = '' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A PRESENTACION ANORMAL DEL FETO NO ESPECIFICADA
actionsDiagnosis['O651'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A ESTRECHEZ GENERAL DE LA PELVIS
actionsDiagnosis['O652'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A DISMINUCION DEL ESTRECHO SUPERIOR DE LA PELVIS
actionsDiagnosis['O654'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A DESPROPORCION FETOPELVIANA, SIN OTRA ESPECIFICACION
actionsDiagnosis['O658'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A OTRAS ANOMALIAS PELVIANAS MATERNAS
actionsDiagnosis['O661'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A DISTOCIA GEMELAR
actionsDiagnosis['O662'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO DEBIDO A DISTOCIA POR FETO INUSUALMENTE GRANDE
actionsDiagnosis['O664'] = '' #FRACASO DE LA PRUEBA DEL TRABAJO DE PARTO, NO ESPECIFICADA
actionsDiagnosis['O669'] = 'VAR_0629 = B' #TRABAJO DE PARTO OBSTRUIDO, SIN OTRA ESPECIFICACION
actionsDiagnosis['O670'] = '' #HEMORRAGIA INTRAPARTO CON DEFECTOS DE LA COAGULACION
actionsDiagnosis['O680'] = '' #TRABAJO DE PARTO Y PARTO COMPLICADOS POR ANOMALIAS DE LA FRECUENCIA CARDIACA FETAL
actionsDiagnosis['O688'] = 'VAR_0633 = B' #TRABAJO DE PARTO Y PARTO COMPLICADOS POR OTRAS EVIDENCIAS DE SUFRIMIENTO FETAL
actionsDiagnosis['O689'] = 'VAR_0633 = B' #SUFRIMIENTO FETAL AGUDO
actionsDiagnosis['O690'] = '' #PROLAPSO DEL CORDON UMBILICAL
actionsDiagnosis['O691'] = '' #CIRCULAR DE CORDON
actionsDiagnosis['O694'] = '' #TRABAJO DE PARTO Y PARTO COMPLICADOS POR VASA PREVIA
actionsDiagnosis['O695'] = '' #TRABAJO DE PARTO Y PARTO COMPLICADOS POR LESION VASCULAR DEL CORDON
actionsDiagnosis['O700'] = 'VAR_0294 = 1' #DESGARRO PERINEAL DE PRIMER GRADO DURANTE EL PARTO
actionsDiagnosis['O701'] = 'VAR_0294 = 2' #DESGARRO PERINEAL DE SEGUNDO GRADO DURANTE EL PARTO
actionsDiagnosis['O702'] = 'VAR_0294 = 3' #DESGARRO PERINEAL DE TERCER GRADO DURANTE EL PARTO
actionsDiagnosis['O709'] = 'VAR_0294 = 0' #DESGARRO PERINEAL DURANTE EL PARTO, DE GRADO NO ESPECIFICADO
actionsDiagnosis['O714'] = '' #DESGARRO VAGINAL OBSTETRICO ALTO, SOLO
actionsDiagnosis['O718'] = '' #OTROS TRAUMAS OBSTETRICOS ESPECIFICADOS
actionsDiagnosis['O719'] = '' #TRAUMA OBSTETRICO, NO ESPECIFICADO
actionsDiagnosis['O721'] = 'VAR_0510 = B' #OTRAS HEMORRAGIAS POSTPARTO INMEDIATAS.
actionsDiagnosis['O722'] = 'VAR_0510 = B' #HEMORRAGIA POSTPARTO SECUNDARIA O TARDIA
actionsDiagnosis['O730'] = '' #RETENCION DE LA PLACENTA SIN HEMORRAGIA
actionsDiagnosis['O751'] = 'VAR_0514 = B' #CHOQUE DURANTE O DESPUES DEL TRABAJO DE PARTO Y EL PARTO
actionsDiagnosis['O752'] = '' #PIREXA DURANTE EL TRABAJO DE PARTO, NO CLASIFICADA EN OTRA PARTE
actionsDiagnosis['O757'] = '' #PARTO VAGINAL POSTERIOR A UNA CESAREA PREVIA
actionsDiagnosis['O800'] = 'VAR_0202 = A' #PARTO UNICO ESPONTANEO, PRESENTACION CEFALICA DE VERTICE
actionsDiagnosis['0800'] = actionsDiagnosis['O800'] 
actionsDiagnosis['O801'] = '' #PARTO UNICO ESPONTANEO, PRESENTACION DE NALGAS O PODALICA
actionsDiagnosis['O808'] = '' #PARTO UNICO ESPONTANEO, OTRAS PRESENTACIONES
actionsDiagnosis['O809'] = '' #PARTO UNICO ESPONTANEO, SIN OTRA ESPECIFICACION
actionsDiagnosis['O820'] = '' #PARTO POR CESAREA ELECTIVA
actionsDiagnosis['O821'] = '' #PARTO POR CESAREA DE EMERGENCIA
actionsDiagnosis['O822'] = '' #PARTO POR CESAREA CON HISTERECTOMIA
actionsDiagnosis['O828'] = '' #OTROS PARTOS UNICOS POR CESAREA
actionsDiagnosis['O829'] = '' #PARTO POR CESAREA, SIN OTRA ESPECIFICACION
actionsDiagnosis['O832'] = '' #OTROS PARTOS UNICOS CON AYUDA DE MANIPULACION OBSTETRICA
actionsDiagnosis['O834'] = '' #OPERACION DESTRUCTIVA PARA FACILITAR EL PARTO
actionsDiagnosis['O838'] = '' #OTROS PARTOS UNICOS ASISTIDOS ESPECIFICADOS
actionsDiagnosis['O839'] = '' #PARTO UNICO ASISTIDO, SIN OTRA ESPECIFICACION
actionsDiagnosis['O840'] = '' #PARTO MULTIPLE, TODOS ESPONTANEOS
actionsDiagnosis['O842'] = '' #PARTO MULTIPLE, TODOS POR CESAREA
actionsDiagnosis['O85X'] = 'VAR_0500 = B' #SEPSIS PUERPERAL
actionsDiagnosis['O862'] = '' #INFECCION DE VIAS URINARIAS CONSECUTIVAS AL PARTO.
actionsDiagnosis['O902'] = '' #HEMATOMA DE HERIDA QUIRÚRGICA OBSTETRICA
actionsDiagnosis['O911'] = '' #ABSCESO DE LA MAMA ASOCIADO CON EL PARTO
actionsDiagnosis['O981'] = '' #SIFILIS EN EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O984'] = '' #HEPATITIS VIRAL QUE COMPLICA EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O986'] = '' #TOXOPLASMOSIS EN EL EMBARAZO
actionsDiagnosis['O988'] = '' #OTRAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS MATERNAS QUE COMPLICAN EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O990'] = 'VAR_0620 = B' #ANEMIA QUE COMPLICA EL EMBARAZO, EL PARTO Y EL PUERPERIO
actionsDiagnosis['O998'] = '' #Induccion del parto con misoprostol
actionsDiagnosis['P000'] = '' #FETO Y RECIEN NACIDO AFECTADOS POR TRASTORNOS HIPERTENSIVOS DE LA MADRE
actionsDiagnosis['P008'] = '' #FETO Y RECIEN NACIDO AFECTADOS POR OTRAS AFECCIONES MATERNAS
actionsDiagnosis['P011'] = '' #FETO Y RECIEN NACIDO AFECTADOS POR RUPTURA PREMATURA DE LAS MEMBRANAS
actionsDiagnosis['P012'] = '' #FETO Y RECIEN NACIDO AFECTADOS POR OLIGOHIDRAMNIOS
actionsDiagnosis['P027'] = 'VAR_0649 = B' #FETO Y RECIEN NACIDO AFECTADOS POR CORIOAMNIONITIS
actionsDiagnosis['P036'] = '' #FETO Y RECIEN NACIDO AFECTADOS POR CONTRACCIONES UTERINAS ANORMALES
actionsDiagnosis['P050'] = 'VAR_0320 = B' #BAJO PESO PARA LA EDAD GESTACIONAL
actionsDiagnosis['P051'] = 'VAR_0320 = B' #PEQUEÑO PARA EDAD GESTACIONAL
actionsDiagnosis['P059'] = 'VAR_0634 = B' #RETARDO DEL CRECIMIENTO FETAL, NO ESPECIFICADO
actionsDiagnosis['P073'] = '' #OTROS RECIEN NACIDOS PRETERMINO
actionsDiagnosis['P285'] = '' #INSUFICIENCIA RESPIRATORIA DEL RECIEN NACIDO
actionsDiagnosis['P371'] = '' #TOXOPLASMOSIS CONGENITA
actionsDiagnosis['P550'] = '' #INCOMPATIBILIDAD RH DEL FETO Y DEL RECIEN NACIDO
actionsDiagnosis['P700'] = '' #SINDROME DEL RECIEN NACIDO DE MADRE CON DIABETES GESTACIONAL
actionsDiagnosis['P708'] = '' #OTROS TRASTORNOS TRANSITORIOS DEL METABOLISMO DE LOS CARBOHIDRATOS EN EL FETO Y EL RECIEN NACIDO
actionsDiagnosis['P743'] = '' #ALTERACIONES DEL EQUILIBRIO DEL POTASIO EN EL RECIEN NACIDO
actionsDiagnosis['P95X'] = '' #MUERTE FETAL DE CAUSA NO ESPECIFICADA
actionsDiagnosis['P964'] = '' #TERMINACION DEL EMBARAZO, QUE AFECTA AL FETO Y AL RECIEN NACIDO
actionsDiagnosis['Q000'] = 'VAR_0335 = C' #ANENCEFALIA
actionsDiagnosis['Q02X'] = 'VAR_0335 = C' #MICROCEFALIA
actionsDiagnosis['Q030'] = 'VAR_0335 = C' #MALFORMACIONES DEL ACUEDUCTO DE SILVIO
actionsDiagnosis['Q070'] = 'VAR_0335 = C' #SINDROME DE ARNOLD-CHIARI
actionsDiagnosis['Q079'] = 'VAR_0335 = C' #MALFORMACION CONGENITA DEL SISTEMA NERVIOSO, NO ESPECIFICADA
actionsDiagnosis['Q209'] = 'VAR_0335 = C' #MALFORMACION CONGENITAS DE LAS CAMARAS CARDIACAS Y SUS CONEXIONES, NO ESPECIFICADA
actionsDiagnosis['Q248'] = 'VAR_0335 = C' #OTRAS MALFORMACIONES CONGENITAS DEL CORAZON, ESPECIFICADAS
actionsDiagnosis['Q258'] = 'VAR_0335 = C' #OTRAS MALFORMACIONES CONGENITAS DE LAS GRANDES ARTERIAS
actionsDiagnosis['Q793'] = '' #GASTROSQUISIS
actionsDiagnosis['Q804'] = 'VAR_0335 = C' #FETO ARLEQUÍN
actionsDiagnosis['Q912'] = 'VAR_0335 = C' #TRISOMIA 18, POR TRANSLOCACION
actionsDiagnosis['R030'] = '' #LECTURA ELEVADA DE LA PRESION SANGUINEA, SIN DIAGNOSTICO DE HIPERTENSION
actionsDiagnosis['R060'] = '' #DISNEA
actionsDiagnosis['R101'] = '' #DOLOR ABDOMINAL LOCALIZADO EN PARTE SUPERIOR
actionsDiagnosis['R102'] = '' #DOLOR PELVICO Y PERINEAL
actionsDiagnosis['R103'] = '' #DOLOR LOCALIZADO EN OTRAS PARTES INFERIORES DEL ABDOMEN
actionsDiagnosis['R104'] = '' #OTROS DOLORES ABDOMINALES Y LOS NO ESPECIFICADOS
actionsDiagnosis['R11X'] = '' #NAUSEA Y VOMITO
actionsDiagnosis['R33X'] = '' #RETENCION DE ORINA
actionsDiagnosis['R500'] = '' #FIEBRE CON ESCALOFRIO
actionsDiagnosis['R520'] = '' #DOLOR AGUDO
actionsDiagnosis['R55X'] = '' #SINCOPE Y COLAPSO
actionsDiagnosis['R571'] = '' #CHOQUE HIPOVOLEMICO
actionsDiagnosis['R58X'] = '' #HEMORRAGIA, NO CLASIFICADA EN OTRA PARTE
actionsDiagnosis['R600'] = '' #EDEMA LOCALIZADO
actionsDiagnosis['R787'] = '' #HALLAZGO DE NIVELES ANORMALES DE METALES PESADOS EN LA SANGRE
actionsDiagnosis['T742'] = '' #ABUSO SEXUAL
actionsDiagnosis['T888'] = '' #OTRAS COMPLICACIONES ESPECIFICADAS DE LA ATENCION MEDICA Y QUIRURGICA, NO CLASIFICADAS EN OTRA PARTE
actionsDiagnosis['Y302'] = '' #CAIDA, SALTO O EMPUJON DESDE LUGAR ELEVADO, DE INTENCION NO DETERMINADA: ESCUELAS, OTRAS INSTITUCIONES Y AREAS ADMINISTRATIVAS
actionsDiagnosis['Y838'] = '' #OTROS PROCEDIMIENTOS QUIRURGICOS
actionsDiagnosis['Z000'] = '' #EXAMEN MEDICO GENERAL
actionsDiagnosis['Z014'] = '' #EXAMEN GINECOLOGICO (GENERAL) (DE RUTINA)
actionsDiagnosis['Z114'] = '' #EXAMEN DE PESQUISA ESPECIAL PARA EL VIRUS DE LA INMUNODEFICIENCIA HUMANA [VIH]
actionsDiagnosis['Z21X'] = '' #ESTADO DE INFECCION ASINTOMATICA POR EL VIRUS DE LA INMUNODEFICIENCIA HUMANA [VIH]
actionsDiagnosis['Z237'] = '' #NECESIDAD DE INMUNIZACION SOLO CONTRA LA TOS FERINA
actionsDiagnosis['Z300'] = '' #CONSEJO Y ASESORAMIENTO GENERAL SOBRE LA ANTICONCEPCION
actionsDiagnosis['Z302'] = '' #ESTERILIZACION
actionsDiagnosis['Z313'] = '' #OTROS METODOS DE ATENCION PARA LA FECUNDACION
actionsDiagnosis['Z314'] = '' #INVESTIGACION Y PRUEBA PARA LA PROCREACION
actionsDiagnosis['Z320'] = '' #EMBARAZO (AUN) NO CONFIRMADO
actionsDiagnosis['Z321'] = '' #EMBARAZO CONFIRMADO
actionsDiagnosis['Z33X'] = '' #ESTADO DE EMBARAZO, INCIDENTAL
actionsDiagnosis['Z340'] = '' #SUPERVISION DE PRIMER EMBARAZO NORMAL
actionsDiagnosis['Z348'] = '' #SUPERVISION DE OTROS EMBARAZOS NORMALES
actionsDiagnosis['Z349'] = '' #SUPERVISION DE EMBARAZO NORMAL NO ESPECIFICADO
actionsDiagnosis['Z350'] = '' #SUPERVISION DE EMBARAZO CON HISTORIA DE ESTERILIDAD
actionsDiagnosis['Z352'] = '' #SUPERVISION DE EMBARAZO CON OTRO RIESGO EN LA HISTORIA OBSTETRICA O REPRODUCTIVA
actionsDiagnosis['Z353'] = '' #EMBARAZO NO CONTROLADO
actionsDiagnosis['Z354'] = '' #GRAN MULTIPARA
actionsDiagnosis['Z355'] = '' #GESTANTE AÑOSA ( PRIMIGESTANTE)
actionsDiagnosis['Z356'] = '' #ADOLESCENTE EMBARAZADA
actionsDiagnosis['Z357'] = '' #SUPERVISION DE EMBARAZO DE ALTO RIESGO DEBIDO A PROBLEMAS SOCIALES
actionsDiagnosis['Z358'] = '' #SUPERVISION DE OTROS EMBARAZOS DE ALTO RIESGO
actionsDiagnosis['Z359'] = '' #ALTO RIESGO OBSTETRICO
actionsDiagnosis['Z370'] = '' #NACIDO VIVO, UNICO
actionsDiagnosis['Z371'] = '' #NACIDO MUERTO, UNICO
actionsDiagnosis['Z372'] = '' #GEMELOS, AMBOS NACIDOS VIVOS
actionsDiagnosis['Z373'] = '' #GEMELOS, UN NACIDO VIVO Y UN NACIDO MUERTO
actionsDiagnosis['Z379'] = '' #PRODUCTO DEL PARTO NO ESPECIFICADO
actionsDiagnosis['Z380'] = '' #PRODUCTO UNICO, NACIDO EN HOSPITAL
actionsDiagnosis['Z381'] = '' #PRODUCTO UNICO, NACIDO FUERA DE HOSPITAL
actionsDiagnosis['Z382'] = '' #PRODUCTO UNICO, LUGAR DE NACIMIENTO NO ESPECIFICADO
actionsDiagnosis['Z390'] = '' #ATENCION Y EXAMEN INMEDIATAMENTE DESPUES DEL PARTO
actionsDiagnosis['Z391'] = '' #ATENCION Y EXAMEN DE MADRE EN PERIODO DE LACTANCIA
actionsDiagnosis['Z392'] = '' #SEGUIMIENTO POSTPARTO, DE RUTINA
actionsDiagnosis['Z488'] = '' #OTROS CUIDADOS ESPECIFICADOS POSTERIORES A LA CIRUGIA
actionsDiagnosis['Z615'] = '' #PROBLEMAS RELACIONADOS CON EL ABUSO SEXUAL DEL NIÑO POR PERSONA AJENA AL GRUPO DE APOYO PRIMARIO
actionsDiagnosis['Z620'] = '' #PROBLEMAS RELACIONADOS CON LA SUPERVISION O EL CONTROL INADECUADOS DE LOS PADRES
actionsDiagnosis['Z640'] = '' #PROBLEMAS RELACIONADOS CON EMBARAZO NO DESEADO
actionsDiagnosis['Z641'] = '' #PROBLEMAS RELACIONADOS CON LA MULTIPARIDAD
actionsDiagnosis['Z659'] = '' #PROBLEMAS RELACIONADOS CON CIRCUNSTANCIAS PSICOSOCIALES NO ESPECIFICADAS
actionsDiagnosis['Z718'] = '' #OTRAS CONSULTAS ESPECIFICADAS
actionsDiagnosis['Z730'] = '' #PROBLEMAS RELACIONADOS CON LA ENFERMEDAD CONSUNTIVA
actionsDiagnosis['Z800'] = '' #HISTORIA FAMILIAR DE TUMOR MALIGNO DE ORGANOS DIGESTIVOS
actionsDiagnosis['Z875'] = '' #HISTORIA PERSONAL DE COMPLICACIONES DEL EMBARAZO, DEL PARTO Y DEL PUERPERIO
actionsDiagnosis['Z892'] = 'VAR_0335 = C' #AUSENCIA ADQUIRIDA DE MIEMBRO SUPERIOR POR ARRIBA DE LA MUÑECA
actionsDiagnosis['Z899'] = 'VAR_0335 = C' #AUSENCIA ADQUIRIDA DE MIEMBROS NO ESPECIFICADOS
actionsDiagnosis['Z970'] = '' # PRESENCIA DE OJO ARTIFICIAL
actionsDiagnosis['Z980'] = '' # ESTADO DE DERIVACION INTESTINAL O ANASTOMOSIS
actionsDiagnosis['Z988'] = '' # OTROS ESTADOS POSTQUIRURGICOS ESPECIFICADOS
actionsDiagnosis['Z998'] = '' # DEPENDENCIA DE OTRAS MAQUINAS Y DISPOSITIVOS CAPACITANTES
actionsDiagnosis['Z864'] = '' # CONSUMO DE SUSTANCIAS PSICOACTIVAS GESTANTE
actionsDiagnosis['D640'] = '' # ANEMIA SIDEROBLASTICA HEREDITARIA
actionsDiagnosis['O338'] = '' # ATENCION MATERNA POR DESPROPORCION DE OTRO ORIGEN
actionsDiagnosis['O439'] = '' # TRASTORNO DE LA PLACENTA, NO ESPECIFICADO
actionsDiagnosis['O619'] = '' # FRACASO NO ESPECIFICADO DE LA INDUCCION DEL TRABAJO DE PARTO
actionsDiagnosis['O710'] = '' #	RUPTURA DEL UTERO ANTES DEL INICIO DEL TRABAJO DE PARTO
actionsDiagnosis['R501'] = '' # FIEBRE PERSISTENTE
actionsDiagnosis['G409'] = '' # EPILEPSIA, TIPO NO ESPECIFICADO
actionsDiagnosis['Z386'] = '' # OTROS NACIMIENTOS MULTIPLES, EN HOSPITAL

