actionMedicament = {} 
actionMedicament["201128"] = "" # Jeringa Desechable 1 ml x 27 G/ 1/2
actionMedicament["INS1021"] = "" # CATGUT 2/0 CT/1 (HR37S) x 90 CM 
actionMedicament["INS121"] = "" # SONDA NELATON # 8 
actionMedicament["INS224"] = "" # Jeringa Desechable 5 ml x 21 G/1 1/2 
actionMedicament["INS225"] = "" # Jeringa Desechable 10 ml x 21 G/1 1/2 
actionMedicament["MD0006"] = "" # ACETAMINOFEN 
actionMedicament["MD0239"] = "" # FITOMENADIONA 
actionMedicament["MD0259"] = "" # GENTAMICINA 3 % 
actionMedicament["MD0430"] = "" # OXITOCINA 
actionMedicament["MD0284"] = "" # SULFATO FERROSO 
actionMedicament["19972965-01"] = "" # SOLUCION SALINA 0.9 %
actionMedicament["51076-02"] = "" # SOLUCION SALINA 0.9 % 
actionMedicament["IM5034"] = "" # MORFINA CLORHIDRATO 
actionMedicament["IM5064"] = "" # LACTATO DE RINGER 
actionMedicament["IM5065"] = "" # LACTATO DE RINGER 
actionMedicament["IM5093"] = "" # RECIPIENTE DE SUCCION FLEXIBLE (LINER) de 3 LT 
actionMedicament["INS001"] = "" # ABOCATH NO. 18 
actionMedicament["INS007"] = "" # EQUIPO MACROGOTEO 
actionMedicament["INS016"] = "" # SONDA NELATON # 16 
actionMedicament["INS039"] = "" # VICRYL 1 CT-1(HR37S) x 90 CM 
actionMedicament["INS042"] = "" # AGUJA ESPINAL TIPO QUINCKE # 27 X 3 1/2 x 90 MM 
actionMedicament["INS089"] = "" # NYLON 3/0 (CDSS24) AGUJA CURVA 
actionMedicament["INS1019"] = "" # CATGUT 0 CT/1 ( HR37S) x 70 CM 
actionMedicament["INS1020"] = "" # CATGUT 1 CT/1 (HR37S) x 90 CM 
actionMedicament["INS127"] = "" # LAPIZ DE ELECTROBISTURI 
actionMedicament["MD0096"] = "" # CEFAZOLINA 
actionMedicament["MD0159"] = "" # DEXAMETASONA FOSFATO 
actionMedicament["MD0199"] = "" # ERGOMETRINA MALEATO  
actionMedicament["MD0237"] = "" # FENTANILO CITRATO 
actionMedicament["MD0378"] = "" # METOCLOPRAMIDA CLORHIDRATO 
actionMedicament["MD0483"] = "" # RANITIDINA CLORHIDRATO  
actionMedicament["MD70052"] = "" # OXITETRACICLINA + POLIMIXINA B OFTALMICA (Terramicina) 
actionMedicament["N02BB02"] = "" # DIPIRONA 
actionMedicament["MD0098"] = "MEOW = A" # CEFRADINA  
actionMedicament["MD0046"] = "" # AMPICILINA  
actionMedicament["IM5059"] = "" # BUPIVACAINA+DEXTROSA (BUPIROP PESADO) 
actionMedicament["IM5073"] = "" # ETILEFRINA 
actionMedicament["IM5112"] = "" # MISOPROSTOL (NO POS) 
actionMedicament["MD0552"] = "" # ACIDO TRANEXAMICO 
actionMedicament["MD0298"] = "" # INMUNOGLOBULINA ANTI D 
actionMedicament["MD0236"] = "" # FENTANILO CITRATO 
actionMedicament["IM5431"] = "" # misOPROStol (NO POS) 
actionMedicament["MD0202"] = "" # ERITROMICINA ETILSUCCINATO O ESTEARATO 
actionMedicament["MD0880"] = "" # BETAMETASONA 
actionMedicament["MD0441"] = "" # PENICILINA G BENZATINICA 
actionMedicament["MD0351"] = "" # SULFATO DE MAGNESIO 
actionMedicament["MD0649"] = "" # NIFEDIPINO 
actionMedicament["IM5130"] = "" # misoPROSTOL (NO POS) 
actionMedicament["MD0685"] = "" # ENOXAPARINA SODICA 
actionMedicament["MD0087"] = "" # CAPTOPRIL
actionMedicament["MD0094"] = "" # CEFALEXINA 
actionMedicament["IM5111"] = "" # RECIPIENTE DE SUCCION FLEXIBLE (LINER) de 1 LT 
actionMedicament["MD0164"] = "" # DEXTROSA EN AGUA DESTILADA 5 % 
actionMedicament["MD90006"] = "" # OXIGENO HUMEDO LITRO 
actionMedicament["MD0260"] = "" # GENTAMICINA SULFATO 
actionMedicament["MD0363"] = "" # MEPERIDINA CLORHIDRATO 
actionMedicament["MD0675"] = "" # CLINDAMICINA  
actionMedicament["19937960-6"] = "" # PROPOFOL 1%
actionMedicament["MD0112"] = "" # CIPROFLOXACINA CLORHIDRATO 
actionMedicament["MD0161"] = "" # DEXTROSA 5% + CLORURO DE SODIO 0.9 % 
actionMedicament["MD0059"] = "" # ATROPINA SULFATO 
actionMedicament["MD0160"] = "" # DEXAMETASONA FOSFATO 
actionMedicament["MD0095"] = "" # CEFALOTINA 
actionMedicament["MD0280"] = "" # HIDROCORTISONA SUCCINATO SODICO  
actionMedicament["MD0072"] = "" # BETAMETILDIGOXINA 
actionMedicament["MD0550"] = "" # TRAMADOL CLORHIDRATO 
actionMedicament["IM5060"] = "" # CEFTRIAXONA 
actionMedicament["IM5018"] = "" # AMPICILINA SODICA + SULBACTAM 
actionMedicament["B01AB05"] = "" # ENOXAPARINA SODICA 
actionMedicament["MD0585"] = "" # ACETATO DE MEDROXIPROGESTERONA PROVERA 
actionMedicament["MD0097"] = "" # CEFRADINA  
actionMedicament["MD0645"] = "" # misoPROSTOL 
actionMedicament["MD0336"] = "" # LIDOCAINA CLORHIDRATO SIN EPINEFRINA 
actionMedicament["51076-03"] = "" # SOLUCION SALINA 0.9 % 
actionMedicament["MD1039"] = "" # ONDANSETRON (NO POS) 
actionMedicament["INS1069"] = "" # TAPON HEPARINIZADO 
actionMedicament["M01AB05"] = "" # DICLOFENACO SODICO 
actionMedicament["MD0189"] = "" # DOXICICLINA 
actionMedicament["MD0292"] = "" # IBUPROFENO 
actionMedicament["MD0644"] = "" # MISOPROSTOL 
actionMedicament["MD0395"] = "" # MIDAZOLAM 
actionMedicament["MD0077"] = "" # BROMOCRIPTINA 
actionMedicament["MD0602"] = "" # CLINDAMICINA (NO POS) 
actionMedicament["MD0186"] = "" # DIPIRONA 
actionMedicament["MD0391"] = "" # METRONIDAZOL 
actionMedicament["MD0449"] = "" # PIPERACILINA+TAZOBACTAM  
actionMedicament["MD0162"] = "" # DEXTROSA EN AGUA DESTILADA 10 % 
actionMedicament["MD70054"] = "" # ZIDOVUDINA 
actionMedicament["MD0597"] = "" # CABERGOLINA  
actionMedicament["MD0408"] = "" # NIFEDIPINO 
actionMedicament["MD1033"] = "" # LABETALOL 
actionMedicament["MD0474"] = "" # PROPRANOLOL CLORHIDRATO 
actionMedicament["MD0467"] = "" # PRAZOSINA 
actionMedicament["MD0208"] = "" # ESPIRONOLACTONA 
actionMedicament["MD0277"] = "" # HIDROCLOROTIAZIDA 
actionMedicament["MD0475"] = "" # PROPRANOLOL CLORHIDRATO 
actionMedicament["IM5119"] = "" # LEVETIRACETAM 
actionMedicament["IM5037"] = "" # PROGESTERONA MICRONIZADA (NO POS) 
actionMedicament["MD0344"] = "" # LORATADINA 
actionMedicament["19953524-1"] = "" # DEXTROSA 5% EN AGUA DESTILADA
actionMedicament["MD0377"] = "" # METOCLOPRAMIDA 
actionMedicament["MD0481"] = "" # RANITIDINA CLORHIDRATO 
actionMedicament["MD0548"] = "" # TRAMADOL CLORHIDRATO 
actionMedicament["MD0421"] = "" # OMEPRAZOL 
actionMedicament["MD1006"] = "" # AZITROMICINA 
actionMedicament["IM5340"] = "" # AZITROMICINA (NO POS) 
actionMedicament["IM5050"] = "" # INHALADOR SALBUTAMOL 
actionMedicament["MD1027"] = "" # ACIDO FOLICO  
actionMedicament["IM5049"] = "" # ENEMA TRAVAD Rectal (NO POS)
actionMedicament["MD0310"] = "" # KETAMINA CLORHIDRATO 
actionMedicament["MD0255"] = "" # FUROSEMIDA 
actionMedicament["MD0195"] = "" # ENALAPRIL MALEATO 
actionMedicament["MD0054"] = "" # ASCORBICO ACIDO 
actionMedicament["MD0124"] = "" # CLONIDINA CLORHIDRATO 
actionMedicament["MD0330"] = "" # LEVOTIROXINA SODICA 
actionMedicament["MD0012"] = "" # ACICLOVIR 
actionMedicament["MD0089"] = "" # CARBAMAZEPINA 
actionMedicament["MD1000"] = "" # ACICLOVIR  
actionMedicament["MD0289"] = "" # N BUTIL BROMURO HIOSCINA 
actionMedicament["MD0416"] = "" # NITROFURANTOINA 
actionMedicament["IM5040"] = "" # ZIDOVUDINA 
actionMedicament["MD0407"] = "" # NEVIRAPINA 
actionMedicament["MD0445"] = "" # PENICILINA G SODICA O POTASICA CRISTALINA 
actionMedicament["MD0079"] = "" # BUPIVACAINA (BUPIROP SIMPLE) 
actionMedicament["IM5439"] = "" # FOSFOMICINA (NO POS) 
actionMedicament["MD0365"] = "" # MEROPENEM 
actionMedicament["MD0337"] = "" # LIDOCAINA CLORHIDRATO CON  EPINEFRINA 2% /0.005 mg 
actionMedicament["MD0027"] = "" # ALUMINIO HIDROXIDO 
actionMedicament["MD0021"] = "" # ALFAMETILDOPA 
actionMedicament["MD1034"] = "" # MEDROXIPROGESTERONA ACETATO 
actionMedicament["MD0681"] = "" # ENOXAPARINA SODICA 
actionMedicament["MD0512"] = "" # SUCCINILCOLINA  
actionMedicament["MD0375"] = "" # METIMAZOL 
actionMedicament["MD0272"] = "" # HALOPERIDOL 
actionMedicament["51076-01"] = "" # SOLUCION SALINA 0.9 % 
actionMedicament["A03DB04"] = "" # N BUTIL BROMURO DE HIOSCINA 20 mg + DIPIRONA 
actionMedicament["MD0422"] = "" # ONDANSETRON (NO POS) 
actionMedicament["MD0033"] = "" # AMIKACINA SULFATO
actionMedicament["MD0372"] = "" # METFORMINA 
actionMedicament["MD0288"] = "" # N BUTIL BROMURO HIOSCINA 
actionMedicament["MD0696"] = "" # INSULINA CRISTALINA 
actionMedicament["MD0697"] = "" # INSULINA N.P.H. 
actionMedicament["MD0286"] = "" # HIERRO PARENTERAL 
actionMedicament["MD0381"] = "" # METOPROLOL TARTRATO 
actionMedicament["MD0424"] = "" # OXACILINA 
actionMedicament["IM5053"] = "" # SALBUTAMOL SULFATO 
actionMedicament["IM5070"] = "" # FENOTEROL BROMHIDRATO 0.50MG+BROMURO DE IPRATROPIO (NO POS) 
actionMedicament["MD0065"] = "" # BECLOMETASONA DIPROPIONATO 
actionMedicament["IM5047"] = "" # BROMURO DE IPRATROPIO
actionMedicament["INS223"] = "" # Jeringa Desechable 20 ml x 21 G/1 1/2 
actionMedicament["IM5449"] = "" # DALTEPARINA SODICA (NO POS) 
actionMedicament["MD0406"] = "" # NEVIRAPINA 
actionMedicament["INS020"] = "" # CANULA NASAL DE OXIGENO ADULTO 
actionMedicament["MD0086"] = "" # CAPTOPRIL 
actionMedicament["MD0356"] = "" # ESTRADIOL 5 MG + MEDROXIPROGESTERONA 
actionMedicament["MD0349"] = "" # LOSARTAN POTASICO 
actionMedicament["IM5398"] = "" # CLOTRIMAZOL 1 % 
actionMedicament["MD0136"] = "" # CLOTRIMAZOL 1 % 
actionMedicament["MD0075"] = "" # BISACODILO 
actionMedicament["MD1035"] = "" # METRONIDAZOL  
actionMedicament["IM5163"] = "" # EQUIPO DE MACROGOTEO (UCIN) 
actionMedicament["M01AE02"] = "" # NAPROXENO TABLETAS 
actionMedicament["MD0584"] = "" # ACETAMINOFEN / FOSFATO DE CODEINA (NO POS) 
actionMedicament["MD0078"] = "" # BUPIVACAINA LEVOGIRA + GLUCOSA (BUPINEST PESADO) 
actionMedicament["MD0206"] = "" # ESPIRAMICINA (3.000.000 m.u.i) 
actionMedicament["MD0024"] = "" # ALPRAZOLAM
actionMedicament["58816-1"] = "" # SEVOFLURANO 
actionMedicament["MD0132"] = "" # CLOROQUINA 250 mg fosfato de cloroquina (150 mg BASE DE CLOROQUINA) 
actionMedicament["MD0682"] = "" # ENOXAPARINA SOLUCION INYECTABLE 
actionMedicament["218170-2"] = "" # BUPIVACAINA (BUPINEST SIMPLE) 
actionMedicament["MD0008"] = "" # ACETIL SALICILICO ACIDO 
actionMedicament["IM5120"] = "" # ACETAMINOFEN (PARACETAMOL) (NO POS) 
actionMedicament["42849-6"] = "" # ADRENALINA 
actionMedicament["MD0165"] = "" # DEXTROSA EN AGUA DESTILADA 50%
actionMedicament["MD0018"] = "" # ALBENDAZOL 
actionMedicament["MD0117"] = "" # CLARITROMICINA 
actionMedicament["MD0032"] = "" # AMIKACINA SULFATO 
actionMedicament["MD0440"] = "" # PENICILINA G BENZATINICA 
actionMedicament["MD0396"] = "" # MIDAZOLAM 
actionMedicament["MD0390"] = "" # METRONIDAZOL 
actionMedicament["IM5447"] = "" # NADROPARINA CALCICA (FRAXIPARINE) 40 mg/0.4 ml
actionMedicament["MD0328"] = "" # LEVONORGESTREL MICRONIZADO (JADELLE) 
actionMedicament["MD1020"] = "" # ENANTATO DE NORESTISTERONA 50mg + VALERATO DE ESTRADIOL 5mg Amp 
actionMedicament["MD0316"] = "" # LAMIVUDINA + ZIDOVUDINA 
actionMedicament["MD0249"] = "" # ACIDO FOLICO 
actionMedicament["MD0004"] = "" # ACETAMINOFEN (150 MG / 5 ML)
actionMedicament["IM5026"] = "" # CLORURO DE POTASIO 
actionMedicament["MD0582"] = "" # REMIFENTANILO 
actionMedicament["MD0196"] = "" # ENALAPRIL MALEATO 
actionMedicament["IM5113"] = "" # SOLUCION SALINA 0.9 % x 500 CC 
actionMedicament["MD0324"] = "" # LEVONORGESTREL 150 mcg + ETINILESTRADIOL 
actionMedicament["IM5007"] = "" # SOLUCION SALINA 0.9 % x 100 CC 
actionMedicament["MD0200"] = "" # ERGOTAMINA + CAFEINA 
actionMedicament["MD0139"] = "" # CLOTRIMAZOL 
actionMedicament["MD0429"] = "" # OXIMETAZOLINA 0.025 % 
actionMedicament["IM5454"] = "" # LAMOTRIGINA
actionMedicament["INS031"] = "" # SONDA FOLEY # 16 Fr DOS VIAS 
actionMedicament["INS034"] = "" # AGUJA ESPINAL TIPO QUINCKE # 26 X 3 1/2 x 90 MM 
actionMedicament["INS046"] = "" # CYSTOFLO BOLSA X 2000 ML 
actionMedicament["MD1001"] = "" # ACICLOVIR 
actionMedicament["IM5023"] = "" # BROMURO DE VECURONIO
actionMedicament["IM5418"] = "" # LIDOCAINA + HIDROCORTISONA ACETATO 
actionMedicament["19972347-1"] = "" # NOREPINEFRINA 
actionMedicament["INS002"] = "" # ABOCATH NO. 20 
actionMedicament["IM5444"] = "" # ACICLOVIR 800 MG
actionMedicament["MD0229"] = "" # FENITOINA SODICA 
actionMedicament["IM5446"] = "" # CARVEDILOL 12.5 MG 
actionMedicament["MD0025"] = "" # ALPRAZOLAM 
actionMedicament["IM5105"] = "" # CLARITROMICINA 
actionMedicament["MD0627"] = "" # HIDROXICLOROQUINA TAB 200 MG 
actionMedicament["MD0374"] = "" # METILPREDNISOLONA  
actionMedicament["MD1040"] = "" # PREDNISOLONA  
actionMedicament["M03AC09"] = "" # BROMURO DE ROCURONIO 
actionMedicament["MD0166"] = "" # DIAZEPAM 
actionMedicament["MD0568"] = "" # VANCOMICINA CLORHIDRATO 
actionMedicament["INS1022"] = "" # CATGUT 2/0 SH (HR26) x 70 CM 
actionMedicament["INS123"] = "" # VICRYL 3-0 CT-1 (HR 37) x 70 CM 
actionMedicament["INS193"] = "" # SEDA 2/0 S/A 
actionMedicament["IM5127"] = "" # CARBETOCINA  
actionMedicament["MD0388"] = "" # METRONIDAZOL BENZOILO 
actionMedicament["MD0045"] = "" # AMOXICILINA 
actionMedicament["IM5352"] = "" # ADENOSINA (NO POS) 
actionMedicament["IM5041"] = "" # PENICILINA G SODICA (1.000.000 UI) 
actionMedicament["MD0256"] = "" # FUROSEMIDA 
actionMedicament["MD1025"] = "" # FLUCONAZOL 
actionMedicament["IM5343"] = "" # INSULINA GLULISINA 
actionMedicament["MD0691"] = "" # FITOSTIMOLINE (NO POS) 
actionMedicament["IM5365"] = "" # LIDOCAINA CLORHIDRATO SIN EPINEFRINA 2 % 
actionMedicament["MD0498"] = "" # SALES DE REHIDRATACION ORAL. 
actionMedicament["IM5080"] = "" # AGUJA ESPINAL TIPO PUNTA DE LAPIZ # 26 G x 90 MM 
actionMedicament["INS261"] = "" # INSULINA GLARGINA (LANTUS) 
actionMedicament["MD0275"] = "" # HEPARINA SODICA 
actionMedicament["IM5438"] = "" # ETONOGESTREL (IMPLANON) (NO POS)
actionMedicament["MD0083"] = "" # GLUCONATO DE CALCIO 10 % 
actionMedicament["IM5442"] = "" # CIANOCOBALAMINA (VITAMINA B12) 
actionMedicament["MD0082"] = "" # CALCIO CARBONATO 
actionMedicament["MD0326"] = "" # LEVONORGESTREL 
actionMedicament["MD0334"] = "" # LIDOCAINA CLORHIDRATO 2% 
actionMedicament["IM5129"] = "" # ONDANSETRON 
actionMedicament["MD0551"] = "" # acido tranEXAMICO 
actionMedicament["MD0405"] = "" # NEOSTIGMINA METILSULFATO  
actionMedicament["B05XA03"] = "" # CLORURO DE SODIO 
actionMedicament["IM5371"] = "" # INMUNOGLOBULINA CONTRA VARICELA ZOSTER 10% (NO POS) 
actionMedicament["MD1022"] = "" # ERTAPENEM (NO POS) 
